# Generated by Django 4.0.4 on 2022-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default='300.0')),
                ('pulse', models.FloatField(default='133.0')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
